server:
  port: 8088

# Veritabanı bağlantı bilgileri
spring:
  application:
    name: investra

  datasource:
    url: jdbc:sqlserver://192.168.144.76:1450;databaseName=Kizikos;encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # Hibernate ayarları
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect

  # Mail ayarları
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      from: Investra Destek <investradestek@gmail.com>

# JWT Secret key değeri
secreteJwtString: ${JWT_SECRET}

app:
#  frontend: ${FRONTEND_URL}
  frontendUrl: ${FRONTEND_URL}
