server:
  port: 8088

# Veritabanı bağlantı bilgileri
spring:
  application:
    name: investra


  # Cache yapılandırması
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 dakika (milisaniye cinsinden)

  datasource:
    url: jdbc:sqlserver://192.168.144.76:1450;databaseName=Kizikos;encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  # Hibernate ayarları
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect

  # Mail ayarları
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      from: Investra Destek <investradestek@gmail.com>

  # Redis yapılandırması
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


# Actuator yapılandırması
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# JWT Secret key değeri
secreteJwtString: ${JWT_SECRET}

app:
#  frontend: ${FRONTEND_URL}
  frontendUrl: ${FRONTEND_URL}
# Logo URL
  logo-url: /images/logo.png

# Infina API Configuration
infina:
  api:
    base-url: https://apitest.infina.com.tr/infina-services/rest/srv/v1.1
    key: XvusCI7S4hyr008JUcPyiAdMSzSHKmWa99VYFXeU
