package com.investra.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {

    // Genel hatalar (1000-1999)
    INTERNAL_ERROR(1000, "Sunucu hatası"),
    INVALID_REQUEST(1001, "Geçersiz istek"),
    DATABASE_ERROR(1002, "Veritabanı hatası"),

    // Doğrulama hataları (2000-2999)
    VALIDATION_ERROR(2000, "Doğrulama hatası"),
    INVALID_CREDENTIALS(2001, "Geçersiz kullanıcı adı veya şifre"),
    INVALID_EMAIL_FORMAT(2002, "Geçersiz e-posta formatı"),
    INVALID_PHONE_FORMAT(2003, "Geçersiz telefon formatı"),
    INVALID_PASSWORD_LENGTH(2004, "Şifre en az 4 karakter uzunluğunda olmalı"),
    INVALID_ARGUMENT(2005, "Geçersiz argüman"),

    // Kaynak bulunamadı hataları (3000-3999)
    RESOURCE_NOT_FOUND(3000, "Kaynak bulunamadı"),
    USER_NOT_FOUND(3001, "Kullanıcı bulunamadı"),
    STOCK_NOT_FOUND(3002, "Hisse senedi bulunamadı"),
    CLIENT_NOT_FOUND(3003, "Müşteri bulunamadı"),
    ACCOUNT_NOT_FOUND(3004, "Hesap bulunamadı"),
    PORTFOLIO_NOT_FOUND(3005, "Portföy bulunamadı"),
    PORTFOLIO_ITEM_NOT_FOUND(3006, "Portföy kalemi bulunamadı"),

    // İzin/Yetki hataları (4000-4999)
    UNAUTHORIZED(4000, "Yetkisiz erişim"),
    FORBIDDEN(4001, "Bu işlem için yetkiniz bulunmamaktadır"),
    ACCESS_DENIED(4002, "Erişim reddedildi"),
    INVALID_OR_EXPIRED_TOKEN(4003, "Geçersiz veya süresi dolmuş token"),

    // İşlem hataları (5000-5999)
    OPERATION_FAILED(5000, "İşlem başarısız"),
    INSUFFICIENT_STOCK(5001, "Yetersiz hisse senedi miktarı"),
    INSUFFICIENT_FUNDS(5002, "Yetersiz bakiye"),
    INSUFFICIENT_BALANCE(5002, "Yetersiz bakiye"), // Alias for INSUFFICIENT_FUNDS
    INACTIVE_STOCK(5003, "Hisse senedi aktif değil"),
    CALCULATION_ERROR(5004, "Hesaplama hatası"),
    MARKET_CLOSED(5005, "Borsa şu anda kapalı"),
    PREVIEW_NOT_CONFIRMED(5006, "Önizleme onaylanmamış"),
    PREVIEW_EXPIRED(5007, "Önizleme süresi dolmuş"),
    UNEXPECTED_ERROR(5008, "Beklenmeyen bir hata oluştu"),
    ACCOUNT_ALREADY_EXISTS(5009, "Hesap zaten mevcut"),
    INVALID_AMOUNT(5010, "Geçersiz tutar"),
    INVALID_PORTFOLIO_CREATE_REQUEST(5011, "Portföy oluşturma isteği geçersiz"),
    INSUFFICIENT_AVAILABLE_BALANCE(5012, "Yetersiz kullanılabilir bakiye"),
    INVALID_ORDER_REQUEST(5013, "Geçersiz emir isteği"),
    ORDER_NOT_FOUND(5014, "Emir bulunamadı"),
    ORDER_ALREADY_EXECUTED(5015, "Emir zaten gerçekleştirilmiş"),
    ORDER_ALREADY_CANCELLED(5016, "Emir zaten iptal edilmiş"),
    INVALID_STOCK_PRICE(5017, "Geçersiz hisse senedi fiyatı"),
    INVALID_QUANTITY(5018, "Geçersiz miktar"),
    INVALID_EXECUTION_TYPE(5019, "Geçersiz gerçekleştirme türü"),
    INVALID_ORDER_TYPE(5020, "Geçersiz emir türü"),
    INVALID_CLIENT_TYPE(5021, "Geçersiz müşteri türü"),
    INVALID_CURRENCY(5022, "Geçersiz para birimi"),
    INVALID_ACCOUNT_TYPE(5023, "Geçersiz hesap türü"),
    INVALID_BROKER_INFO(5024, "Geçersiz aracı kurum bilgisi"),
    INVALID_CUSTODIAN_INFO(5025, "Geçersiz saklama bankası bilgisi"),
    INVALID_IBAN(5026, "Geçersiz IBAN"),
    INVALID_ACCOUNT_NUMBER(5027, "Geçersiz hesap numarası"),
    INVALID_NICKNAME(5028, "Geçersiz hesap adı"),
    INVALID_INITIAL_BALANCE(5029, "Geçersiz başlangıç bakiyesi"),
    INVALID_TRANSACTION_DATE(5030, "Geçersiz işlem tarihi"),
    INVALID_DESCRIPTION(5031, "Geçersiz açıklama"),
    INVALID_USER_EMAIL(5032, "Geçersiz kullanıcı e-posta adresi"),
    INVALID_PASSWORD(5033, "Geçersiz şifre"),
    INVALID_EMPLOYEE_NUMBER(5034, "Geçersiz çalışan numarası"),
    INVALID_CLIENT_STATUS(5035, "Geçersiz müşteri durumu"),
    INVALID_CLIENT_SEARCH_TERM(5036, "Geçersiz müşteri arama terimi"),
    INVALID_STOCK_CODE(5037, "Geçersiz hisse senedi kodu"),
    INVALID_STOCK_NAME(5038, "Geçersiz hisse senedi adı"),
    INVALID_STOCK_GROUP(5039, "Geçersiz hisse senedi grubu"),
    INVALID_STOCK_SOURCE(5040, "Geçersiz hisse senedi kaynağı"),
    INVALID_STOCK_PRICE_UPDATE(5041, "Geçersiz hisse senedi fiyat güncellemesi"),
    INVALID_PORTFOLIO_ITEM(5042, "Geçersiz portföy kalemi"),
    INVALID_PORTFOLIO_VALUATION(5043, "Geçersiz portföy değerlemesi"),
    INVALID_TRADE_ORDER(5044, "Geçersiz alım-satım emri"),
    INVALID_TRANSACTION(5045, "Geçersiz işlem"),
    INVALID_NOTIFICATION(5046, "Geçersiz bildirim"),
    INVALID_REPORT(5047, "Geçersiz rapor"),
    INVALID_LOG(5048, "Geçersiz log"),
    INVALID_SIMULATION_DATE(5049, "Geçersiz simülasyon tarihi"),
    INVALID_END_OF_DAY_PROCESS(5050, "Geçersiz gün sonu işlemi"),
    INVALID_TRANSACTION_VOLUME(5051, "Geçersiz işlem hacmi"),
    INVALID_LIMIT_ORDER_PRICE(5052, "Limit emirleri için fiyat bilgisi zorunludur ve sıfırdan büyük olmalıdır"),
    MARKET_ORDER_PRICE_NOT_ALLOWED(5053, "Market emirlerinde fiyat bilgisi gereksizdir ve kullanılamaz"),
    PREVIEW_ID_REQUIRED(5054, "Preview ID gereklidir"),
    PREVIEW_ID_EMPTY(5055, "Preview ID boş olamaz"),
    PREVIEW_NOT_FOUND_OR_EXPIRED(5056, "Geçersiz veya süresi dolmuş önizleme ID'si"),
    PREVIEW_WRONG_TYPE(5057, "Önizleme yanlış türde"),
    PREVIEW_EXPIRED_OR_NOT_FOUND(5058, "Önizleme bulunamadı veya süresi doldu"),
    PREVIEW_EXPIRED_DUPLICATE(5059, "Önizleme süresi doldu"),
    INVALID_ORDER_PARAMETERS(5060, "Emir parametreleri geçersiz"),
    CLIENT_OR_STOCK_INFO_EMPTY(5061, "Müşteri veya hisse senedi bilgisi boş olamaz"),
    INVALID_PRICE(5062, "Geçersiz fiyat"),
    CALCULATION_ARITHMETIC_ERROR(5063, "Hesaplama sırasında aritmetik hata oluştu"),
    CALCULATION_INVALID_PARAMETER(5064, "Hesaplama için geçersiz parametre"),
    CALCULATION_UNEXPECTED_ERROR(5065, "Hesaplama sırasında beklenmeyen bir hata oluştu"),
    ACCOUNT_STOCK_CALCULATION_INFO_EMPTY(5066, "Hesap, hisse senedi veya hesaplama bilgisi boş olamaz"),
    PREVIEW_RESPONSE_CREATION_ERROR(5067, "Önizleme yanıtı oluşturulurken bir hata oluştu"),
    PORTFOLIO_UPDATE_ERROR(5068, "Portföy güncellenirken bir hata oluştu"),
    PORTFOLIO_UPDATE_UNEXPECTED_ERROR(5069, "Portföy güncellenirken beklenmeyen bir hata oluştu"),
    ACCOUNT_BALANCE_UPDATE_ERROR(5070, "Hesap bakiyesi güncellenirken bir hata oluştu"),
    ACCOUNT_BALANCE_UPDATE_UNEXPECTED_ERROR(5071, "Hesap bakiyesi güncellenirken beklenmeyen bir hata oluştu"),
    BUY_ORDER_UPDATE_ERROR(5072, "Alış işlemi sonrası güncelleme yapılırken hata oluştu"),
    CLIENT_PORTFOLIO_NOT_FOUND(5073, "Müşterinin portföyü bulunamadı"),
    SELL_ORDER_UPDATE_ERROR(5074, "Satış işlemi sonrası güncelleme yapılırken hata oluştu"),
    ENTITY_SEARCH_ERROR(5075, "Varlıklar aranırken bir hata oluştu"),
    ENTITY_SEARCH_UNEXPECTED_ERROR(5076, "Varlıklar aranırken beklenmeyen bir hata oluştu"),
    USER_SEARCH_ERROR(5077, "Kullanıcı aranırken bir hata oluştu"),
    USER_SEARCH_UNEXPECTED_ERROR(5078, "Kullanıcı aranırken beklenmeyen bir hata oluştu"),
    EMAIL_SENDING_ERROR(5079, "Email gönderilirken hata oluştu"),
    EMAIL_TEMPLATE_PROCESSING_ERROR(5080, "Email şablonu işlenirken hata oluştu"),
    INSUFFICIENT_STOCK_IN_PORTFOLIO(5081, "Portföyde yeterli hisse senedi bulunmuyor"),
    STOCK_NOT_FOUND_IN_PORTFOLIO(5082, "Portföyde satılacak hisse senedi bulunamadı"),
    MULTIPLE_PORTFOLIO_FOUND(5083, "Client için birden fazla portföy bulundu. Veri bütünlüğü problemi!"),
    ORDER_INFO_EMPTY(5084, "Emir bilgisi boş olamaz"),
    END_OF_DAY_PRICES_NOT_UPDATED(5085, "Gün sonu fiyatları henüz güncellenmedi"),
    PORTFOLIO_VALUATION_NOT_FOUND(5086, "Bu müşteri için değerleme bulunamadı"),
    PORTFOLIO_VALUATION_FAILED(5087, "Bu müşteri için değerleme yapılamadı"),
    DAY_ADVANCE_FAILED(5088, "Gün atlatma işlemi başarısız"),
    CLIENT_NAME_EMPTY(5089, "Müşteri adı boş olamaz"),
    BIRTH_DATE_EMPTY(5090, "Doğum tarihi boş olamaz"),
    GENDER_EMPTY(5091, "Cinsiyet bilgisi boş olamaz"),
    ADDRESS_EMPTY(5092, "Adres bilgisi boş olamaz"),
    CURRENT_PASSWORD_INCORRECT(5093, "Mevcut şifre hatalı"),
    NEW_PASSWORD_MISMATCH(5094, "Yeni şifre ve şifre tekrarı eşleşmiyor"),
    USER_NOT_FOUND_BY_EMAIL(5095, "Bu e-posta adresi ile kayıtlı bir kullanıcı bulunamadı"),
    PASSWORD_RESET_EMAIL_ERROR(5096, "Şifre sıfırlama e-postası gönderilirken bir hata oluştu"),
    EMAIL_SENDING_FAILED(5097, "E-posta gönderimi sırasında bir hata oluştu"),
    NOTIFICATION_PROCESSING_ERROR(5098, "Bildirim işlemi sırasında beklenmeyen bir hata oluştu"),

    // Bildirim hataları (6000-6999)
    NOTIFICATION_ERROR(6000, "Bildirim gönderimi başarısız"),
    EMAIL_SENDING_ERROR_LEGACY(6001, "E-posta gönderimi başarısız");

    private final int code;
    private final String message;
}